#Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

global: &global
  twitter_key: <%= ENV["TWITTER_KEY"] %>
  twitter_secret: <%= ENV["TWITTER_SECRET"] %>
  s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

development:
  secret_key_base: b4e2aabd3a2d219cf25c7bbc33b95722bcd1d18fcbc33ce7febd5908857705da134f39babd0dad622c8cfa96c04d734b0fef9625b09f3f0dcc90f3bea73d08c6
  <<: *global

test:
  secret_key_base: 162ecde4d4fe5ef88c30f6f9baa9e6465f5d31db3d794401d0a74f87fd2a3275690d69192073ce607804c21203d63e1ec373304514661f30b7ff170270e54fd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *global
